default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: quartesian_assessment_development

test:
  <<: *default
  database: quartesian_assessment_test


production:
  <<: *default
  database: quartesian_assessment_production
  username: quartesian_assessment
  password: <%= ENV['QUARTESIAN_ASSESSMENT_DATABASE_PASSWORD'] %>
